ChainOfStories/ChainOfStories/Controllers/CultureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChainOfStories.Controllers
{
    public class CultureController : Controller
    {
        public ActionResult SetCulture(string actName, string lang, int? id)
        {
            var cookie = new HttpCookie("CultureInfo")
            {
                Value = lang
            };
            Response.Cookies.Add(cookie);
            return RedirectToAction(actName, "Home", new { id = id });
        }
    }
}

ChainOfStories/ChainOfStories/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/css/sb-admin.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Content/ckeditor/ckeditor.js"></script>
    <script src="~/Content/ckeditor/adapters/jquery.js"></script>
    <script type="text/javascript">
        $('.ckeditor').ckeditor();
    </script>
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/Admin/Index">Panel Ana Sayfa</a>
                <a class="navbar-brand" href="~/Home" target="_blank">Site Önizleme</a>
            </div>
            <ul class="nav navbar-right top-nav">
                <a href="~/Home/AdminLogOut"><button type="button" class="btn btn-default" style="margin-top: 8px;margin-right: 20px;"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Çıkış</button></a>
            </ul>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="/Writer/Index"><i class="fa fa-fw fa-dashboard"></i>Kullanıcılar</a>
                    </li>
                    <li>
                        <a href="/Story/Index"><i class="fa fa-fw fa-edit"></i>Hikayeler </a>
                    </li>
                    <li>
                        <a href="/News/Index"><i class="fa fa-fw fa-bar-chart-o"></i>Haberler</a>
                    </li>
                    <li>
                        <a href="/SlidePhoto/Index"><i class="fa fa-fw fa-bar-chart-o"></i>Slayt Resimleri</a>
                    </li>
                    <li>
                        <a href="/Page/About"><i class="fa fa-fw fa-edit"></i>Hakkımızda Sayfası</a>
                    </li>
                    <li>
                        <a href="/Contact/Index"><i class="fa fa-fw fa-edit"></i>Mesajlar</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

ChainOfStories/ChainOfStories/Views/Shared/_Layout.cshtml
@using ChainOfStories.Resource
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>    
    <!-- css -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/fancybox/jquery.fancybox.css" rel="stylesheet">
    <link href="~/Content/jcarousel.css" rel="stylesheet" />
    <link href="~/Content/flexslider.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />    
    <!-- Theme skin -->
    <link href="~/Content/skins/default.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper">
        <!-- start header -->
        <header>
            <div class="navbar navbar-default navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="~/Home/Index"><span>C</span>hain of Stories</a>
                    </div>
                    <div class="navbar-collapse collapse ">
                        <ul class="nav navbar-nav">
                            <li class="index"><a href="~/Home/Index">@Resource.AnaSayfa</a></li>
                            <li class="stories"><a href="~/Home/Stories">@Resource.Hikayeler</a></li>
                            <li class="news"><a href="~/Home/News">@Resource.Haberler</a></li>
                            <li class="aboutUs"><a href="~/Home/AboutUs">@Resource.Hakkimizda</a></li>
                            <li class="contact"><a href="~/Home/Contact">@Resource.Iletisim</a></li>
                            @{
                                if (Request.Cookies["User"] == null)
                                {
                                    <li class="contact"><a href="~/Home/Login">@Resource.Girisyap</a></li>
                                }
                                else
                                {
                                    <li class="contact"><a href="~/Home/LogOut">@Resource.Cikisyap</a></li>
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        <!-- end header -->
        @RenderBody()
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <a href="@Url.Action("SetCulture", "Culture", new { actName = ViewContext.RouteData.Values["action"], Lang = "tr-TR", id = ViewContext.RouteData.Values["id"] }, null)">
                            TR
                        </a> |
                        <a href="@Url.Action("SetCulture", "Culture", new { actName = ViewContext.RouteData.Values["action"], Lang = "en-US", id = ViewContext.RouteData.Values["id"] }, null)">
                            EN
                        </a>
                    </div>
                </div>
            </div>
            <div id="sub-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="copyright">
                                <p>
                                    <span>&copy; Moderna 2014 All right reserved. By </span><a href="http://bootstraptaste.com" target="_blank">Bootstrap Themes</a>
                                </p>
                                <!--
                                    All links in the footer should remain intact.
                                    Licenseing information is available at: http://bootstraptaste.com/license/
                                    You can buy this theme without footer links online at: http://bootstraptaste.com/buy/?theme=Moderna
                                -->
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <ul class="social-network">
                                <li><a href="#" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
                                <li><a href="#" data-placement="top" title="Google plus"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/jquery.easing.1.3.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.fancybox.pack.js"></script>
    <script src="~/Scripts/jquery.fancybox-media.js"></script>
    <script src="~/Scripts/google-code-prettify/prettify.js"></script>
    <script src="~/Scripts/portfolio/jquery.quicksand.js"></script>
    <script src="~/Scripts/portfolio/setting.js"></script>
    <script src="~/Scripts/jquery.flexslider.js"></script>
    <script src="~/Scripts/animate.js"></script>
    <script src="~/Scripts/custom.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>