ChainOfStories/ChainOfStories/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dto;

namespace ChainOfStories.Controllers
{
    [AdminAuthorize]
    public class PageController : BaseController
    {
        public ActionResult About()
        {
            var aboutPage = PageFacade.GetPageLocalesByPage("AboutUs");
            return View(aboutPage);
        }
        public ActionResult Edit(int id)
        {
            var page = PageFacade.GetPageLocaleById(id);
            return View(page);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, [Bind(Include = "Description")]PageList page)
        {
            if (!ModelState.IsValid)
            {
                var currentPage = PageFacade.GetItem(id);
                return View(currentPage);
            }
            page.LocaleId = id;
            PageFacade.UpdateItem(page);
            return RedirectToAction("/About");
        }
    }
}

ChainOfStories/ChainOfStories/Views/Page/About.cshtml
@model IList<Dto.PageList>

@{
    ViewBag.Title = "Hakkımızda Sayfası";
}

<h2>Hakkımızda Sayfası</h2>

<div>
    <table class="table">
        <tr>
            <th>Dil</th>
            <th>Açıklama</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Lang</td>
                <td>@item.Description</td>
                <td>@Html.ActionLink("Düzenle", "Edit", new { id = item.LocaleId }, new { @class = "btn btn-default" }) </td>
            </tr>
        }
    </table>

</div>

ChainOfStories/ChainOfStories/Views/Page/Edit.cshtml
@model Dto.PageList
@using System.Web.Mvc
@{
    ViewBag.Title = "Hakkımızda Sayfası Düzenle";
}

<h3>Hakkımızda Sayfası (@Model.Lang) <small>Düzenle</small></h3>
@using (Html.BeginForm("Edit", "Page", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="form-group">
        <label for="Description">Açıklama</label>
        <textarea class="form-control ckeditor" name="Description" id="Description" rows="4">@Model.Description</textarea>
        @Html.ValidationMessageFor(model => model.Description)
    </div>
    <div class="form-group">
        <div class="btn-group">
            <input type="submit" class="btn btn-default" value="Düzenle" />
            <a href="~/Page/About" class="btn btn-default">İptal</a>
        </div>
    </div>
}